baseurl = "https://maxstatdocumentation.netlify.app/"
languageCode = "en-us"
title = "Max's StatPage"
theme = "hugo-ivy"
disablePathToLower = true
googleAnalytics = ""
disqusShortname = "https-maxstatdocumentation-netlify-app"
ignoreFiles = [
  "\\.Rmd$",
  "\\.Rmarkdown$",
  "_cache$",
  "\\.knit\\.md$",
  "\\.utf8\\.md$"
]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"

[permalinks]
note = "/note/:year/:month/:day/:slug/"
post = "/post/:year/:month/:day/:slug/"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Posts"
url = "/post/"
weight = 2

[[menu.main]]
name = "Notes"
url = "/note/"
weight = 3

[[menu.main]]
name = "Categories"
url = "/categories/"
weight = 4

[[menu.main]]
name = "About"
url = "/info"
weight = 5



[params]
description = "Stat Student, Data Analysis Nerd, Chinese Speaker"
footer = "&copy; [Max Lang](https://maxstatdocumentation.netlify.app/) 2020 | [Github](https://github.com/MaxMLang)"
highlightjsCDN = "//cdn.bootcss.com"
highlightjsLang = [ "r", "yaml", "tex" ]
highlightjsTheme = "github"
highlightjsVersion = "9.12.0"

[markup.goldmark.renderer]
unsafe = true


