 baseurl: 'https://maxstatdocumentation.netlify.app/'
languageCode: en-us
title: Max's StatPage
theme: hugo-ivy
disablePathToLower: true
googleAnalytics: ''
disqusShortname: https-maxstatdocumentation-netlify-app
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$
preserveTaxonomyNames: true
footnotereturnlinkcontents: ↩
permalinks:
  note: '/note/:year/:month/:day/:slug/'
  post: '/post/:year/:month/:day/:slug/'
menu:
  main:
    - name: Home
      url: /
      weight: 1
    - name: Posts
      url: /post/
      weight: 2
    - name: Categories
      url: /categories/
      weight: 3
    - name: Tags
      url: /tags/
      weight: 4
    - name: About
      url: /about/
      weight: 5
    - name: Notes
      url: /note/
params:
  description: 'Stat Student, Data Analysis Nerd, Chinese Speaker'
  footer: >-
    &copy; [Max Lang](https://maxstatdocumentation.netlify.app/) 2020 |
    [Github](https://github.com/MaxMLang)
  highlightjsCDN: //cdn.bootcss.com
  highlightjsLang:
    - r
    - yaml
    - tex
  highlightjsTheme: github
  highlightjsVersion: 9.12.0
markup:
  goldmark:
    renderer:
      unsafe: true
