---
title: Digital work, social life and the new roblems
author: Max Lang
date: '2021-01-07'
slug: digital-work-and-social-life-and-its-problems
categories:
  - Other
  - Discussion
tags: []
---

# How Covid generated an (almost) complete digital World.

During the Covid-19 pandemic everybody was and still is forced to stay home. Countries
have enacted harsh lockdown laws and everybody was feeling the power of the state again
after a really long time. Some more, some less.
It is interesting however, how this "new" life is bringing up new problems.
"Should I meet my friends or is it too dangerous, because of the current situation?", "Oh no, another Zoom Meeting how am I gonna survive this?" are all 
questions that we asked ourselves probably for the first time ever. 
I created a short list of three major topics that have been discussed at an discussion of the Konrad-Adenauer-Stiftung Thinktank.

1. _Health_

Working from home has one big advantage regarding health: Minimizing the risk of an infection. That is perfect, but it also creates other issues concerning our physical and mental health.

_Physical health problems_

*Back and neck pain*

Sitting is bad for the human spine. We were all build by nature to walk around hunt and gather, not to sit in front of a black mirror everyday, trying to hunt solutions for math problems. 
A hurting neck and back are the result. 

*What can you do about it?*

* Do small stretching exercises every 30 Minutes and walk one round through your room after two hours. ([Good streetching exercises](https://www.healthline.com/health/deskercise#arms))

* Buy a gymnastic Ball and use at as a desk chair now and then

*Eye pain*

Looking at a computer everyday is exhausting. No I am not ironic it really is, but for your eyes. The blue light is not good for your eyes and you can feel it. It burns and your eyes are dry like a desert, but you do not really have an option but to continue. 

*What can you do about it?*
* Turn on the *blue light filter* on your laptop

* Take breaks were you do *not* check your phone or look at any screen. 

* Close your eyes and just rest (but don't fall asleep)


_Mental health problems_

The lockdown is a  real psychological challenge, especially if you live alone. I had one of the worst months of my life, while I was alone and with nobody to talk (face to face) during the lockdown in Singapore. It messes with you. Your anxiety gets higher every day, you feel sleepy all the time and you just close up (emotionally). We need literally need a social life to work efficient. So do not underestiamte the psychological consequences of Covid.

*What can you do about it?*
* Establish daily routines and stick to them
* Make a work plan everyday and stick to it
* Call people via Zoom or phone and just talk
* Listen to  podcasts in case you feel alone

2. _Productivity_

We actually discussed a lot of problems regarding productivity in home offices, so I just want to layout the most common one almost everybody had.

The challenge of to work and live at the same place is enormous, even though it seems pretty straightforward. That is why people underestimate it. 
We came to the conclusion that everyone either works not enough and procrastinates or works way to much and can not get his minds of work. (I am the second kind and it is a real severe problem for me)

It is hard to find the right balance between working and chilling, because everything happens at the same place. (For me even in the same room in my small apartment in Munich)

*What can you do about it*

_not working enough (procrastinating)_

+ Divde your apartment into "work-space" and "living-space". This will help you focus better on your work. So do not watch Netflix at your desk and do not answer E-Mails from your phone on the couch

+ Establish a daily morning routine (Get up early, go to the bathroom, brush your teeth... ) and stick to it. It really helps starting your day right.

+ Make a "To-do" list every evening when you stop working and cross of your tasks you today.(This will give you a kick in motivation, because you are proud what you did today)
+ Dress like you would go to work

+ Become clear about your Why? Why are you doing this, why do you want to do it (not why you have to)

+ Have your goals in front of you and I mean literally in front of you! Take a piece of paper and write down long-term and short term goals. Post it somewhere you can see it everyday e.g. your desk, door etc. (also multiple locations are possible). This technique sounds stupid at first, but it really helps becoming clear about your "Why?". You will not lose motivation

_working too much_

+ Set breaks and really stick to them

+ Call people you love or like and talk with thenm

+ If you finished your "To-Do" list really stop working!

+ Decide on a clear shutdown time, e.g 8 pm

3. _Social responsibility_

We all have responsibility, especially now. Every contact we make, every time we are not sticking to the hygienic rules, we not only risk us, but everybody around us. We all know that and say/think we are responsible but are we acting responsible? What should you do, if your uncle invites you to a family reunion (5+ people)? What would they think if you decline? It would make you look like you do not care about them. How would you feel if you go there? Probably uncomfortable, because there are so many people of all ages. So what do you do? It is a tough decision and we probably all have been there. It is a real dilemma no matter what you choose there is no real pro.

*What can you do about it ?*

* Communication is key, talk to the people, explain it thoroughly 
* Accept their decisions and do not judge them or tell them what they should do
* Be open for critique on your decisions but explain them your point of view
* Do not start fighting, it is not worth it
* Safe over fun!

# Thoughts

Those were the top 3 topics and the result from the discussion. I really enjoyed this event and it was nice to share opinions and strategies to battle the new problems/challenges (depending on if you think the glass is half full or empty ^^) that came up with our new working and social life during this pandemic. 

Stay safe everyone!







