---
title: Epsilon Delta Proof (continuity)
author: Max Lang
date: '2021-01-14'
slug: epsilon-delta-proof-continuity
categories:
  - Mathematics
  - Proof
tags: []
---

We are living in crazy times. Everything that was normal before has changed during the Covid-19 pandemic. That might make you wonder: "What did not change?", "Are qudratic polynoms still continous?". Ok, nobody did/would ever say this (LOL), but I really did not know how to introduce this topic. 

In my Calculus class we introduced the Definition of conituity a couple of weeks ago which is the following

Let $M \subseteq \mathbb{C}, \zeta \in M .$ Fkt. $f: M \longrightarrow \mathbb{K}$ is called continous in $\zeta$ if and only if 
$$
\begin{array}{ccc}
\forall & \exists & \forall \\
\epsilon>0 & \delta>0 & z \in M
\end{array}(|z-\zeta|<\delta \Rightarrow|f(z)-f(\zeta)|<\epsilon)
$$

This basically just says that a small change on the X-Axis will result in a small change on the Y-Axis. To get a better visual perspective on this you can play a bit with this [GeoGebra illusstration]{https://www.geogebra.org/m/cxbjrvks}. 

So our goal is to prove that the following function is continuous with an Epsilon Delta Argument.
$$ f: \mathbb R^2 \rightarrow \mathbb R^2 \;  x\mapsto(x^2+2x+1)$$

The first step is always to figure out the delta. Therefore we start to simplify $|f(z)-f(\zeta)|<\epsilon$.

So I started with 

(★) $$\left\lvert f(x)-f(y) \right\rvert= \left\lvert (x^2+2x+1) - (y^2+2y+1) \right\rvert = \left\lvert (x^2+2x)-(y^2+2y) \right\rvert$$

$$\le 2\left\lvert \left\lvert \frac{x^2-y^2}{2} \right\rvert + \left\lvert x- y\right\rvert \right\rvert $$
$$\le 2\left\lvert \left\lvert \frac{(x+y)(x-y)}{2} \right\rvert + \delta \right\rvert$$
$$= 2\left\lvert \frac{\left\lvert(x+y)(x-y)\right\rvert}  {2} + \delta \right\rvert $$
$$ \le 2\left\lvert \frac{\left\lvert(x+y)\delta\right\rvert}  {2} + \delta \right\rvert $$
$$= 2\left\lvert \frac{[\left\lvert(x-y)\right\rvert+\left\lvert2y\right\rvert]\delta}  {2} + \delta \right\rvert $$

Because we can set any requirements for our Delta we let Delta be $\delta \le1.$ This means that our two points on the X-Axis can not be further apart than 1. Now we can substitute $(x-y)$ for 1.

$$= 2\left\lvert \frac{(1+\left\lvert2y\right\rvert)\delta}  {2} + \delta \right\rvert $$
$$= \left\lvert(1+\left\lvert2y\right\rvert)\delta + 2\delta \right\rvert $$
$$= \delta \left\lvert(1+\left\lvert2y\right\rvert) + 2 \right\rvert $$
$$= \delta \left\lvert\left\lvert2y\right\rvert + 3 \right\rvert = \epsilon $$
$\delta = min\left(1, \frac{\epsilon}{\left\lvert\left\lvert2y\right\rvert + 3 \right\rvert} \right)$ 

So that was a lot of Algebra, but we made it. Now we can write our formal proof.

Given $\epsilon>0,$ let $\delta= min\left(1, \frac{\epsilon}{\left\lvert\left\lvert2y\right\rvert + 3 \right\rvert} \right)$.  If $0<|x-y|<\delta$ then (★), so $|f(x)-L|<\epsilon$ and $f$ is therefore continuous. So we could insert it into the Definition and it would like this.
$$
\begin{array}{ccc}
\forall & \exists & \forall \\
\epsilon>0 & \delta>0 & x \in \mathbb R
\end{array}(|x-y|<min\left(1, \frac{\epsilon}{\left\lvert\left\lvert2y\right\rvert + 3 \right\rvert} \right) \Rightarrow|f(x)-f(y)|< \delta \left\lvert\left\lvert2y\right\rvert + 3 \right\rvert)
$$

# Thoughts
So what can we take from this? Not everything has changed because of Covid-19, Polynoms are still continuous. Nice! 
If you take some time and reconsider the Definition of a continuous function, you find out it actually is a pretty genius way of describing continuity. However, nothing new, nothing special just describing obvious facts precisely. 

*Pure mathematics is, in its way, the poetry of logical ideas.* - Albert Einstein